config/routes.rb
Posts::Application.routes.draw do
  

  resources :posts

   root :to => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new

	end

	def create
		@post = Post.new(post_params)

		@post.save
		redirect_to @post
	end

	def show
		@post = Post.find(params[:id])
	end

	private
	def post_params
		params[:post]
	end

	#def post_params
		#params.require(:post).permit(:title, :content)
	#end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>List of Posts</h1>
<table>

	<tr>
		<th>Title</th>
		<th>Content</th>
	</tr>

	<% @posts.each do |p| %>
		<tr>
			<td><%= p.title %></td>
			<td><%= p.content %></td>
		</tr>
	<% end %>

</table>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, :url => posts_path do|f| %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content %>
		<%= f.text_area :content %>
	</p>

	<p>
		<%= f.submit "Submit" %>
	</p>

<% end %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<p>
<strong>Title:</strong>
<%= @post.title %>
</p>
<p>
<strong>Content:</strong>
<%= @post.content %>
</p>
<%= link_to "Back", posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Posts", controller: 'posts' %>